# Generated by Django 4.1 on 2022-09-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Totmarks', models.IntegerField()),
                ('City', models.CharField(max_length=40)),
                ('RefreshToken', models.CharField(max_length=1500)),
                ('Email', models.CharField(max_length=80, unique=True)),
                ('Passwd', models.CharField(max_length=40)),
            ],
        ),
    ]
